# Generated by Django 5.2.3 on 2025-06-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('freshers', 'Freshers'), ('entry', 'Entry Level'), ('mid', 'Mid Level'), ('experienced', 'Experienced'), ('senior', 'Senior Level'), ('executive', 'Executive')], max_length=20),
        ),
    ]
