services:
  - type: web
    name: jobportal-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn job.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jobportal.settings
      - key: SECRET_KEY
        value: django-insecure-87g4^#gkwt%c+(zdak=%=k&b^-!b%tl!5v1%$t21)m-mc6&f@_
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.10
      # Add your own environment variables here 
      
